all: assignment.cu
	nvcc pinnable.cu -L /usr/local/cuda/lib -lcudart -o pinnable.exe
	nvcc pageable.cu -L /usr/local/cuda/lib -lcudart -o pageable.exe
	nvcc caesar_cipher.cu -L /usr/local/cuda/lib -lcudart -o caesar_cipher.exe
